In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
import numpy as np

## 1. LÀM SẠCH DỮ LIỆU

In [ ]:
df_02_diem = pd.read_excel('/content/drive/MyDrive/MyComputer/Learning/Khai thác dữ liệu và ứng dụng - CS313.N21/Education_dataset_V2/02.diem.xlsx', sheet_name='02 diem')
df_02_diem

,id,mssv,mamh,malop,sotc,namhoc,hocky,diem,trangthai,mamh_tt
0,137424.0,31D5D488XPvAibaEXe85Kg8gbEhwbxD0x3mi2el8,CS1113,CS1113.D11,4.0,2012.0,1.0,0.0,2.0,NULL
1,140865.0,31D5D488XPvAibaEXe85Kg8gbEhwbxD0x3mi2el8,PH001,PH001.D11,4.0,2012.0,1.0,0.0,1.0,NULL
2,141624.0,31D5D488XPvAibaEXe85Kg8gbEhwbxD0x3mi2el8,ENGL1113,ENGL1113.D11CTTT,3.0,2012.0,1.0,0.0,2.0,NULL
3,141651.0,31D5D488XPvAibaEXe85Kg8gbEhwbxD0x3mi2el8,ADENG1,ADENG1.D11CTTT,0.0,2012.0,1.0,0.0,2.0,NULL
4,141684.0,31D5D488XPvAibaEXe85Kg8gbEhwbxD0x3mi2el8,SS001,SS001.D11CTTT,5.0,2012.0,1.0,0.0,2.0,NULL
...,...,...,...,...,...,...,...,...,...,...
99094,NaN,577C2F7AXPvAibaEXe+02ryNj/uIX7kQnyK7nQCD,IT005,IT005.H21,4.0,2016.0,2.0,5.3,1.0,NULL)
99095,NaN,D1C33C40XPvAibaEXe9xHju59ydahS2HvMczzT5k,IT005,IT005.H21,4.0,2016.0,2.0,4.2,2.0,NULL)
99096,NaN,882FB1B0XPvAibaEXe8y6/RMXZRwBebw/cEMIAJK,IT005,IT005.H21,4.0,2016.0,2.0,0.0,1.0,NULL)
99097,NaN,2FCE0D1DXPvAibaEXe+4XPPXlKRz0GVlqKh+FNRG,IT005,IT005.H21,4.0,2016.0,2.0,0.0,1.0,NULL)
99098,NaN,709876F2XPvAibaEXe9fw8mX+aV2oweP33XrQ8TL,IT005,IT005.H21,4.0,2016.0,2.0,5.2,1.0,NULL

In [ ]:
df_02_diem.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99099 entries, 0 to 99098
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          20000 non-null  float64
 1   mssv        98963 non-null  object
 2    mamh       98963 non-null  object
 3    malop      98963 non-null  object
 4    sotc       98963 non-null  float64
 5    namhoc     98963 non-null  float64
 6    hocky      98963 non-null  float64
 7    diem       98928 non-null  float64
 8    trangthai  98963 non-null  float64
 9    mamh_tt    98963 non-null  object
dtypes: float64(6), object(4)
memory usage: 7.6+ MB

In [ ]:
# Chuẩn hóa tên cột (xóa khoảng trắng đầu mỗi tên cột)
df_02_diem = df_02_diem.rename(columns={' mssv': 'mssv',
                                        ' mamh': 'mamh',
                                        ' malop': 'malop',
                                        ' sotc': 'sotc',
                                        ' namhoc': 'namhoc',
                                        ' hocky': 'hocky',
                                        ' diem': 'diem',
                                        ' trangthai': 'trangthai',
                                        ' mamh_tt': 'mamh_tt'})

In [ ]:
# Xóa các dòng không có mssv
df_02_diem = df_02_diem.dropna(subset=['mssv'])

In [ ]:
df_02_diem.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 98963 entries, 0 to 99098
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         20000 non-null  float64
 1   mssv       98963 non-null  object
 2   mamh       98963 non-null  object
 3   malop      98963 non-null  object
 4   sotc       98963 non-null  float64
 5   namhoc     98963 non-null  float64
 6   hocky      98963 non-null  float64
 7   diem       98928 non-null  float64
 8   trangthai  98963 non-null  float64
 9   mamh_tt    98963 non-null  object
dtypes: float64(6), object(4)
memory usage: 8.3+ MB

In [ ]:
df_02_diem = df_02_diem.drop('id', axis=1)

In [ ]:
df_02_diem['mamh'].unique()

array([' CS1113', ' PH001', ' ENGL1113', ' ADENG1', ' SS001', ' MA003',
       ' MA001', ' IT001', ' PE001', ' MATH2144', ' PE002', ' SPCH3724',
       ' EN001', ' MA002', ' EN002', ' ENBT', ' PH002', ' CE101',
       ' CE104', ' CE114', ' IT007', ' SMET2', ' CS2133', ' ADENG2',
       ' IT002', ' EN003', ' SE312', ' SE323', ' IT008', ' CS105',
       ' IT003', ' PH003', ' MA004', ' MA005', ' IT004', ' IS402',
       ' MATH2153', ' IT005', ' IT009', ' NT307', ' SS004', ' SE104',
       ' ENGL1213', ' NT116', ' ITEM1', ' SS002', ' SS003', ' IT006',
       ' SE102', ' WINP1', ' CE118', ' CE103', ' CS3653', ' MATH3013',
       ' CS4343', ' CS221', ' NT113', ' NT305', ' SE330', ' PHYS1114',
       ' NT104', ' NT106', ' IS210', ' CE105', ' IS253', ' IE103',
       ' SPCH3723', ' IS232', ' IS105', ' NT119', ' CS3443', ' CS5423',
       ' NT111', ' SS005', ' NT118', ' IS201', ' CS511', ' CS106',
       ' SE114', ' SE106', ' NT101', ' CS406', ' IS215', ' IS213',
       ' SE220', ' CE119', ' IS334', ' IE102', ' SC203', ' PHYS1214',
       ' SE332', ' SE107', ' IS254', ' NT334', ' CS4793', ' CE222',
       ' IS207', ' IS216', ' EN004', ' EN005', ' CE404', ' IE104',
       ' NT112', ' NT105', ' IE105', ' CS3373', ' STAT4033', ' NT103',
       ' SE101', ' CS111', ' SE341', ' IS251', ' SE215', ' CS112',
       ' CS110', ' NT503', ' CE117', ' CS4283', ' NT130', ' SE301',
       ' NT206', ' CS313', ' NT204', ' NT131', ' NT201', ' SE340',
       ' NT208', ' NT109', ' CS214', ' IS336', ' IS403', ' NT331',
       ' EC202', ' IS208', ' CS217', ' IS217', ' SE346', ' SE100',
       ' IS353', ' EC203', ' SE108', ' IE106', ' CS4323', ' NT330',
       ' CS3363', ' CS519', ' SE111', ' EN006', ' EC201', ' NT332',
       ' CE107', ' NT209', ' NT333', ' IS252', ' IS211', ' CE315',
       ' CE212', ' CE221', ' CE316', ' MSIS4523', ' CS4243', ' MSIS3303',
       ' NT303', ' IE303', ' EC302', ' SE334', ' IE101', ' NT405',
       ' CS314', ' SE313', ' CS211', ' CS113', ' CS521', ' CS2433',
       ' SE325', ' CS524', ' CS226', ' CS326', ' SE109', ' CS412',
       ' NT205', ' SE310', ' CS4273', ' SE214', ' SE331', ' CS316',
       ' NT114', ' NT117', ' EC301', ' EC001', ' CS301', ' IS212',
       ' CS3613', ' NT115', ' CS5433', ' IE202', ' CE211', ' CS3423',
       ' NT402', ' NT211', ' IS335', ' CS5030', ' NT532', ' CS409',
       ' ADENG3', ' NT210', ' CS222', ' CS323', ' CS325', ' CS410',
       ' IS405', ' SE221', ' MSIS3033', ' IE206', ' NT406', ' CE401',
       ' IS219', ' SE501', ' CS420', ' CS315', ' SE112', ' CE201',
       ' CE326', ' CS302', ' IE403', ' MSIS4263'], dtype=object)

In [ ]:
# Chuẩn hóa cột mamh
for index, value in df_02_diem['mamh'].iteritems():
    df_02_diem['mamh'][index] = value.replace("'", "").replace(" ", "")
print(df_02_diem['mamh'])

<ipython-input-16-1e40cc97cf7b>:2: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for index, value in df_02_diem['mamh'].iteritems():
<ipython-input-16-1e40cc97cf7b>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_02_diem['mamh'][index] = value.replace("'", "").replace(" ", "")

0          CS1113
1           PH001
2        ENGL1113
3          ADENG1
4           SS001
           ...
99094       IT005
99095       IT005
99096       IT005
99097       IT005
99098       IT005
Name: mamh, Length: 98963, dtype: object

In [ ]:
df_02_diem['mamh'].unique()

array(['CS1113', 'PH001', 'ENGL1113', 'ADENG1', 'SS001', 'MA003', 'MA001',
       'IT001', 'PE001', 'MATH2144', 'PE002', 'SPCH3724', 'EN001',
       'MA002', 'EN002', 'ENBT', 'PH002', 'CE101', 'CE104', 'CE114',
       'IT007', 'SMET2', 'CS2133', 'ADENG2', 'IT002', 'EN003', 'SE312',
       'SE323', 'IT008', 'CS105', 'IT003', 'PH003', 'MA004', 'MA005',
       'IT004', 'IS402', 'MATH2153', 'IT005', 'IT009', 'NT307', 'SS004',
       'SE104', 'ENGL1213', 'NT116', 'ITEM1', 'SS002', 'SS003', 'IT006',
       'SE102', 'WINP1', 'CE118', 'CE103', 'CS3653', 'MATH3013', 'CS4343',
       'CS221', 'NT113', 'NT305', 'SE330', 'PHYS1114', 'NT104', 'NT106',
       'IS210', 'CE105', 'IS253', 'IE103', 'SPCH3723', 'IS232', 'IS105',
       'NT119', 'CS3443', 'CS5423', 'NT111', 'SS005', 'NT118', 'IS201',
       'CS511', 'CS106', 'SE114', 'SE106', 'NT101', 'CS406', 'IS215',
       'IS213', 'SE220', 'CE119', 'IS334', 'IE102', 'SC203', 'PHYS1214',
       'SE332', 'SE107', 'IS254', 'NT334', 'CS4793', 'CE222', 'IS207',
       'IS216', 'EN004', 'EN005', 'CE404', 'IE104', 'NT112', 'NT105',
       'IE105', 'CS3373', 'STAT4033', 'NT103', 'SE101', 'CS111', 'SE341',
       'IS251', 'SE215', 'CS112', 'CS110', 'NT503', 'CE117', 'CS4283',
       'NT130', 'SE301', 'NT206', 'CS313', 'NT204', 'NT131', 'NT201',
       'SE340', 'NT208', 'NT109', 'CS214', 'IS336', 'IS403', 'NT331',
       'EC202', 'IS208', 'CS217', 'IS217', 'SE346', 'SE100', 'IS353',
       'EC203', 'SE108', 'IE106', 'CS4323', 'NT330', 'CS3363', 'CS519',
       'SE111', 'EN006', 'EC201', 'NT332', 'CE107', 'NT209', 'NT333',
       'IS252', 'IS211', 'CE315', 'CE212', 'CE221', 'CE316', 'MSIS4523',
       'CS4243', 'MSIS3303', 'NT303', 'IE303', 'EC302', 'SE334', 'IE101',
       'NT405', 'CS314', 'SE313', 'CS211', 'CS113', 'CS521', 'CS2433',
       'SE325', 'CS524', 'CS226', 'CS326', 'SE109', 'CS412', 'NT205',
       'SE310', 'CS4273', 'SE214', 'SE331', 'CS316', 'NT114', 'NT117',
       'EC301', 'EC001', 'CS301', 'IS212', 'CS3613', 'NT115', 'CS5433',
       'IE202', 'CE211', 'CS3423', 'NT402', 'NT211', 'IS335', 'CS5030',
       'NT532', 'CS409', 'ADENG3', 'NT210', 'CS222', 'CS323', 'CS325',
       'CS410', 'IS405', 'SE221', 'MSIS3033', 'IE206', 'NT406', 'CE401',
       'IS219', 'SE501', 'CS420', 'CS315', 'SE112', 'CE201', 'CE326',
       'CS302', 'IE403', 'MSIS4263'], dtype=object)

In [ ]:
df_02_diem['malop'].unique()

array([' CS1113.D11', ' PH001.D11', ' ENGL1113.D11CTTT', ...,
       ' IS207.H22', ' MSIS4263.H21.CTTT', ' IT005.H21'], dtype=object)

In [ ]:
# Chuẩn hóa cột malop
for index, value in df_02_diem['malop'].iteritems():
    df_02_diem['malop'][index] = value.replace("'", "").replace(" ", "")
print(df_02_diem['malop'])

<ipython-input-20-c7dad4274f70>:2: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for index, value in df_02_diem['malop'].iteritems():
<ipython-input-20-c7dad4274f70>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_02_diem['malop'][index] = value.replace("'", "").replace(" ", "")

0              CS1113.D11
1               PH001.D11
2        ENGL1113.D11CTTT
3          ADENG1.D11CTTT
4           SS001.D11CTTT
               ...
99094           IT005.H21
99095           IT005.H21
99096           IT005.H21
99097           IT005.H21
99098           IT005.H21
Name: malop, Length: 98963, dtype: object

In [ ]:
df_02_diem['malop'].unique()

array(['CS1113.D11', 'PH001.D11', 'ENGL1113.D11CTTT', ..., 'IS207.H22',
       'MSIS4263.H21.CTTT', 'IT005.H21'], dtype=object)

In [ ]:
# Đồng nhất kiểu dữ liệu
df_02_diem['sotc'] = df_02_diem['sotc'].astype(int)
df_02_diem['namhoc'] = df_02_diem['namhoc'].astype(int)
df_02_diem['hocky'] = df_02_diem['hocky'].astype(int)
df_02_diem['trangthai'] = df_02_diem['trangthai'].astype(int)

In [ ]:
df_02_diem['diem'].unique()

array([ 0. ,  2.5,  7. ,  5.5,  4.5,  5. ,  7.5,  4. ,  6. ,  6.5,  9. ,
        3.5,  8.5,  8. , 10. ,  9.5,  2. ,  3. ,  1.5,  1. ,  0.5,  4.7,
        8.6,  7.6,  6.7,  5.8,  0.9,  5.7,  5.9,  8.2,  5.4,  6.1,  7.2,
        6.9,  6.6,  6.2,  7.7,  7.3,  6.4,  7.4,  7.8,  6.8,  8.1,  9.3,
        7.1,  5.6,  9.8,  5.2,  8.8,  9.2,  8.9,  8.4,  3.1,  5.3,  3.4,
        9.1,  2.7,  4.6,  6.3,  3.7,  9.6,  9.7,  9.4,  8.3,  9.9,  8.7,
        7.9,  2.8,  4.8,  3.8,  4.9,  2.3,  2.6,  3.9,  4.1,  4.4,  3.2,
        2.1,  4.3,  1.8,  5.1,  3.3,  1.4,  1.2,  2.4,  0.7,  0.6,  0.8,
        4.2,  1.1,  1.6,  1.3,  2.2,  2.9,  3.6,  1.7,  0.2,  0.4,  1.9,
        0.3,  0.1,  nan])

In [ ]:
df_02_diem['diem'] = df_02_diem['diem'].astype(float)

In [ ]:
df_02_diem['mamh_tt'].unique()

array([' NULL', ' NULL);', ' NULL)', " 'EN005')", " 'EN002')",
       " 'EN003')", " 'SE107')", " 'CS105')", " 'NT103')"], dtype=object)

In [ ]:
# Chuẩn hóa cột mamh_tt
for index, value in df_02_diem['mamh_tt'].iteritems():
    df_02_diem['mamh_tt'][index] = value.replace("'", "").replace(" ", "").replace(")", "").replace(";", "")
print(df_02_diem['mamh_tt'])

<ipython-input-24-5fbf4ce4ea33>:2: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for index, value in df_02_diem['mamh_tt'].iteritems():
<ipython-input-24-5fbf4ce4ea33>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_02_diem['mamh_tt'][index] = value.replace("'", "").replace(" ", "").replace(")", "").replace(";", "")

0        NULL
1        NULL
2        NULL
3        NULL
4        NULL
         ...
99094    NULL
99095    NULL
99096    NULL
99097    NULL
99098    NULL
Name: mamh_tt, Length: 98963, dtype: object

In [ ]:
# Chuyển NULL về np.NaN
df_02_diem['mamh_tt'] = df_02_diem['mamh_tt'].replace('NULL', np.nan)
print(df_02_diem['mamh_tt'])

0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
        ...
99094    NaN
99095    NaN
99096    NaN
99097    NaN
99098    NaN
Name: mamh_tt, Length: 98963, dtype: object

In [ ]:
df_02_diem['mamh_tt'].unique()

array([nan, 'EN005', 'EN002', 'EN003', 'SE107', 'CS105', 'NT103'],
      dtype=object)

In [ ]:
df_02_diem.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 98963 entries, 0 to 99098
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   mssv       98963 non-null  object
 1   mamh       98963 non-null  object
 2   malop      98963 non-null  object
 3   sotc       98963 non-null  int64
 4   namhoc     98963 non-null  int64
 5   hocky      98963 non-null  int64
 6   diem       98928 non-null  float64
 7   trangthai  98963 non-null  int64
 8   mamh_tt    12 non-null     object
dtypes: float64(1), int64(4), object(4)
memory usage: 9.6+ MB

In [ ]:
print(df_02_diem)

                                           mssv      mamh             malop  \
0      31D5D488XPvAibaEXe85Kg8gbEhwbxD0x3mi2el8    CS1113        CS1113.D11
1      31D5D488XPvAibaEXe85Kg8gbEhwbxD0x3mi2el8     PH001         PH001.D11
2      31D5D488XPvAibaEXe85Kg8gbEhwbxD0x3mi2el8  ENGL1113  ENGL1113.D11CTTT
3      31D5D488XPvAibaEXe85Kg8gbEhwbxD0x3mi2el8    ADENG1    ADENG1.D11CTTT
4      31D5D488XPvAibaEXe85Kg8gbEhwbxD0x3mi2el8     SS001     SS001.D11CTTT
...                                         ...       ...               ...
99094  577C2F7AXPvAibaEXe+02ryNj/uIX7kQnyK7nQCD     IT005         IT005.H21
99095  D1C33C40XPvAibaEXe9xHju59ydahS2HvMczzT5k     IT005         IT005.H21
99096  882FB1B0XPvAibaEXe8y6/RMXZRwBebw/cEMIAJK     IT005         IT005.H21
99097  2FCE0D1DXPvAibaEXe+4XPPXlKRz0GVlqKh+FNRG     IT005         IT005.H21
99098  709876F2XPvAibaEXe9fw8mX+aV2oweP33XrQ8TL     IT005         IT005.H21

       sotc  namhoc  hocky  diem  trangthai mamh_tt
0         4    2012      1   0.0          2     NaN
1         4    2012      1   0.0          1     NaN
2         3    2012      1   0.0          2     NaN
3         0    2012      1   0.0          2     NaN
4         5    2012      1   0.0          2     NaN
...     ...     ...    ...   ...        ...     ...
99094     4    2016      2   5.3          1     NaN
99095     4    2016      2   4.2          2     NaN
99096     4    2016      2   0.0          1     NaN
99097     4    2016      2   0.0          1     NaN
99098     4    2016      2   5.2          1     NaN

[98963 rows x 9 columns]

In [ ]:
df_02_diem.to_csv('/content/drive/MyDrive/MyComputer/Learning/Khai thác dữ liệu và ứng dụng - CS313.N21/edu_data_v2/02_diem.csv', index=False)

# 2. Phân tích dữ liệu

In [ ]:
df_02_diem = pd.read_csv('/content/drive/MyDrive/MyComputer/Learning/Khai thác dữ liệu và ứng dụng - CS313.N21/edu_data_v2/02_diem.csv')

In [ ]:
df_02_diem

,mssv,mamh,malop,sotc,namhoc,hocky,diem,trangthai,mamh_tt
0,31D5D488XPvAibaEXe85Kg8gbEhwbxD0x3mi2el8,CS1113,CS1113.D11,4,2012,1,0.0,2,NaN
1,31D5D488XPvAibaEXe85Kg8gbEhwbxD0x3mi2el8,PH001,PH001.D11,4,2012,1,0.0,1,NaN
2,31D5D488XPvAibaEXe85Kg8gbEhwbxD0x3mi2el8,ENGL1113,ENGL1113.D11CTTT,3,2012,1,0.0,2,NaN
3,31D5D488XPvAibaEXe85Kg8gbEhwbxD0x3mi2el8,ADENG1,ADENG1.D11CTTT,0,2012,1,0.0,2,NaN
4,31D5D488XPvAibaEXe85Kg8gbEhwbxD0x3mi2el8,SS001,SS001.D11CTTT,5,2012,1,0.0,2,NaN
...,...,...,...,...,...,...,...,...,...
98958,577C2F7AXPvAibaEXe+02ryNj/uIX7kQnyK7nQCD,IT005,IT005.H21,4,2016,2,5.3,1,NaN
98959,D1C33C40XPvAibaEXe9xHju59ydahS2HvMczzT5k,IT005,IT005.H21,4,2016,2,4.2,2,NaN
98960,882FB1B0XPvAibaEXe8y6/RMXZRwBebw/cEMIAJK,IT005,IT005.H21,4,2016,2,0.0,1,NaN
98961,2FCE0D1DXPvAibaEXe+4XPPXlKRz0GVlqKh+FNRG,IT005,IT005.H21,4,2016,2,0.0,1,NaN
98962,709876F2XPvAibaEXe9fw8mX+aV2oweP33XrQ8TL,IT005,IT005.H21,4,2016,2,5.2,1,NaN

In [ ]:
# Thống kê số lượng NA của từng cột
df_02_diem.isna().sum()

mssv             0
mamh             0
malop            0
sotc             0
namhoc           0
hocky            0
diem            35
trangthai        0
mamh_tt      98951
dtype: int64

In [ ]:
df_02_diem.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 98963 entries, 0 to 98962
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   mssv       98963 non-null  object
 1   mamh       98963 non-null  object
 2   malop      98963 non-null  object
 3   sotc       98963 non-null  int64
 4   namhoc     98963 non-null  int64
 5   hocky      98963 non-null  int64
 6   diem       98928 non-null  float64
 7   trangthai  98963 non-null  int64
 8   mamh_tt    12 non-null     object
dtypes: float64(1), int64(4), object(4)
memory usage: 6.8+ MB

In [ ]:
# Tính điểm trung bình học kì của một sinh viên
def diem_tb_hk_nh(masv, hocky, namhoc, diem):
    # Lọc các môn học của sinh viên trong học kỳ và năm học tương ứng
    filtered_data = diem[(diem['masv'] == masv) & (diem['hocky'] == hocky) & (diem['namhoc'] == namhoc)]
    
    # Lọc các môn học có trạng thái học tập bình thường, trả nợ hoặc cải thiện
    filtered_data = filtered_data[filtered_data['trangthai'].isin([1, 2, 3])]
    
    # Loại bỏ các môn học có số tín chỉ bằng 0
    filtered_data = filtered_data[filtered_data['sotc'] > 0]
    
    # Tính tổng số tín chỉ và tổng điểm của các môn học
    tong_sotc = filtered_data['sotc'].sum()
    tong_diem = 0
    
    for index, row in filtered_data.iterrows():
        tong_diem += float(row['diem']) * row['sotc']
    
    diem_tb_hk_nh = tong_diem / tong_sotc
    return diem_tb_hk_nh

In [ ]:
df_02_diem['diem_tb_hk'] = df_02_diem.groupby(['masv', 'namhoc', 'hocky']).apply(lambda x: diem_tb_hk_nh(x.name[0], x.name[2], x.name[1], x)).reset_index(level=[0, 1, 2], drop=True)
df_02_diem

In [ ]:
# Tính điểm trung bình toàn khóa của một sinh viên 
def diem_tb_tk(masv, hocky, namhoc, diem):
    # Lọc các môn học của sinh viên trong học kỳ và năm học tương ứng
    filtered_data = diem[(diem['masv'] == masv) & (diem['hocky'] == hocky) & (diem['namhoc'] == namhoc)]
    
    # Lọc các môn học có trạng thái học tập bình thường, trả nợ hoặc cải thiện
    filtered_data = filtered_data[filtered_data['trangthai'].isin([1])]
    
    # Loại bỏ các môn học có số tín chỉ bằng 0
    filtered_data = filtered_data[filtered_data['sotc'] > 0]
    
    # Tính tổng số tín chỉ và tổng điểm của các môn học
    tong_sotc = filtered_data['sotc'].sum()
    tong_diem = 0
    
    for index, row in filtered_data.iterrows():
        tong_diem += float(row['diem']) * row['sotc']
    
    diem_tb_tk = tong_diem / tong_sotc
    return diem_tb_tk

In [ ]:
df_02_diem['diem_tb_tk'] = df_02_diem.groupby(['masv', 'namhoc', 'hocky']).apply(lambda x: diem_tb_tk(x.name[0], x.name[2], x.name[1], x)).reset_index(level=[0, 1, 2], drop=True)
df_02_diem

<ipython-input-22-340bc49b2ec8>:19: RuntimeWarning: invalid value encountered in long_scalars
  diem_tb_tk = tong_diem / tong_sotc

,masv,mamh,malop,sotc,namhoc,hocky,diem,trangthai,mamh_tt,diem_tb_hk,diem_tb_tk
0,31D5D488XPvAibaEXe85Kg8gbEhwbxD0x3mi2el8,CS1113,CS1113.D11,4,2012,1,0.0,2,NaN,5.333333,6.250000
1,31D5D488XPvAibaEXe85Kg8gbEhwbxD0x3mi2el8,PH001,PH001.D11,4,2012,1,0.0,1,NaN,2.807692,6.500000
2,31D5D488XPvAibaEXe85Kg8gbEhwbxD0x3mi2el8,ENGL1113,ENGL1113.D11CTTT,3,2012,1,0.0,2,NaN,7.070588,7.070588
3,31D5D488XPvAibaEXe85Kg8gbEhwbxD0x3mi2el8,ADENG1,ADENG1.D11CTTT,0,2012,1,0.0,2,NaN,6.363636,6.777778
4,31D5D488XPvAibaEXe85Kg8gbEhwbxD0x3mi2el8,SS001,SS001.D11CTTT,5,2012,1,0.0,2,NaN,7.634783,7.634783
...,...,...,...,...,...,...,...,...,...,...,...
98958,378A030FXPvAibaEXe/ggdm4YTR3E0iXAo9i7YhT,IT005,IT005.H21,4,2016,2,5.3,1,NaN,NaN,NaN
98959,201D2295XPvAibaEXe/ggdm4YTR3EzRR9G2Gpv0E,IT005,IT005.H21,4,2016,2,4.2,2,NaN,NaN,NaN
98960,4D956155XPvAibaEXe/ggdm4YTR3E+z4zTaeOVn1,IT005,IT005.H21,4,2016,2,0.0,1,NaN,NaN,NaN
98961,CC65EE2AXPvAibaEXe/ggdm4YTR3EzzbAtbyRSjO,IT005,IT005.H21,4,2016,2,0.0,1,NaN,NaN,NaN
98962,93AA5B04XPvAibaEXe/ggdm4YTR3E+o03NmVa5LV,IT005,IT005.H21,4,2016,2,5.2,1,NaN,NaN,NaN

In [4]:
df = pd.read_csv('/content/drive/MyDrive/MyComputer/Learning/Khai thác dữ liệu và ứng dụng - CS313.N21/edu_data_v2/02_diem.csv')
df

,mssv,mamh,malop,sotc,namhoc,hocky,diem,trangthai,mamh_tt
0,31D5D488XPvAibaEXe85Kg8gbEhwbxD0x3mi2el8,CS1113,CS1113.D11,4,2012,1,0.0,2,NaN
1,31D5D488XPvAibaEXe85Kg8gbEhwbxD0x3mi2el8,PH001,PH001.D11,4,2012,1,0.0,1,NaN
2,31D5D488XPvAibaEXe85Kg8gbEhwbxD0x3mi2el8,ENGL1113,ENGL1113.D11CTTT,3,2012,1,0.0,2,NaN
3,31D5D488XPvAibaEXe85Kg8gbEhwbxD0x3mi2el8,ADENG1,ADENG1.D11CTTT,0,2012,1,0.0,2,NaN
4,31D5D488XPvAibaEXe85Kg8gbEhwbxD0x3mi2el8,SS001,SS001.D11CTTT,5,2012,1,0.0,2,NaN
...,...,...,...,...,...,...,...,...,...
98958,577C2F7AXPvAibaEXe+02ryNj/uIX7kQnyK7nQCD,IT005,IT005.H21,4,2016,2,5.3,1,NaN
98959,D1C33C40XPvAibaEXe9xHju59ydahS2HvMczzT5k,IT005,IT005.H21,4,2016,2,4.2,2,NaN
98960,882FB1B0XPvAibaEXe8y6/RMXZRwBebw/cEMIAJK,IT005,IT005.H21,4,2016,2,0.0,1,NaN
98961,2FCE0D1DXPvAibaEXe+4XPPXlKRz0GVlqKh+FNRG,IT005,IT005.H21,4,2016,2,0.0,1,NaN
98962,709876F2XPvAibaEXe9fw8mX+aV2oweP33XrQ8TL,IT005,IT005.H21,4,2016,2,5.2,1,NaN

In [6]:
df = df.loc[:, ['mssv', 'sotc', 'diem', 'trangthai']]
df

                                           mssv  sotc  diem  trangthai
0      31D5D488XPvAibaEXe85Kg8gbEhwbxD0x3mi2el8     4   0.0          2
1      31D5D488XPvAibaEXe85Kg8gbEhwbxD0x3mi2el8     4   0.0          1
2      31D5D488XPvAibaEXe85Kg8gbEhwbxD0x3mi2el8     3   0.0          2
3      31D5D488XPvAibaEXe85Kg8gbEhwbxD0x3mi2el8     0   0.0          2
4      31D5D488XPvAibaEXe85Kg8gbEhwbxD0x3mi2el8     5   0.0          2
...                                         ...   ...   ...        ...
98958  577C2F7AXPvAibaEXe+02ryNj/uIX7kQnyK7nQCD     4   5.3          1
98959  D1C33C40XPvAibaEXe9xHju59ydahS2HvMczzT5k     4   4.2          2
98960  882FB1B0XPvAibaEXe8y6/RMXZRwBebw/cEMIAJK     4   0.0          1
98961  2FCE0D1DXPvAibaEXe+4XPPXlKRz0GVlqKh+FNRG     4   0.0          1
98962  709876F2XPvAibaEXe9fw8mX+aV2oweP33XrQ8TL     4   5.2          1

[98963 rows x 4 columns]

In [7]:
df.to_csv('/content/drive/MyDrive/MyComputer/Learning/Khai thác dữ liệu và ứng dụng - CS313.N21/02_diem.csv', index=False)