In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
import numpy as np

## 1. LÀM SẠCH DỮ LIỆU

In [5]:
df_sinhvien_dtb_hocky = pd.read_excel('/content/drive/MyDrive/MyComputer/Learning/Khai thác dữ liệu và ứng dụng - CS313.N21/Education_dataset_V2/sinhvien_dtb_hocky.xlsx',
                               sheet_name='uit_sinhvienttct')
df_sinhvien_dtb_hocky

                                           mssv  hocky  namhoc  dtbhk  sotchk
0      48685401XPvAibaEXe99yNsueYx+scOnjQSx4nXO      1    2016   6.45      13
1      48685401XPvAibaEXe99yNsueYx+scOnjQSx4nXO      2    2016   5.86      17
2      48685401XPvAibaEXe99yNsueYx+scOnjQSx4nXO      1    2017   6.54      16
3      48685401XPvAibaEXe99yNsueYx+scOnjQSx4nXO      2    2017   5.67      23
4      48685401XPvAibaEXe99yNsueYx+scOnjQSx4nXO      1    2018   2.27      21
...                                         ...    ...     ...    ...     ...
84947  EA2A92C2XPvAibaEXe99J3nD1pBZIshWCsT6VhsJ      1    2022   6.70       3
84948  ED5A0E45XPvAibaEXe/CiPILllTJf8s+lllUG7Kd      1    2022   7.80       3
84949  09DE3A51XPvAibaEXe/GEP39G15BdRSEDU3D3+LV      2    2022   0.00       0
84950  CCF627D0XPvAibaEXe+oAybUv81bbkc8L/mx+IhC      2    2022   0.00       0
84951  A6169055XPvAibaEXe81r7KrCH0uc4QKxDeoWYb4      2    2022   0.00       0

[84952 rows x 5 columns]

In [6]:
df_sinhvien_dtb_hocky.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 84952 entries, 0 to 84951
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   mssv    84952 non-null  object
 1   hocky   84952 non-null  int64
 2   namhoc  84952 non-null  int64
 3   dtbhk   84952 non-null  float64
 4   sotchk  84952 non-null  int64
dtypes: float64(1), int64(3), object(1)
memory usage: 3.2+ MB