In [6]:
import pandas as pd

In [57]:
df = pandas.read_excel('/content/drive/MyDrive/Khai thác dữ liệu và ứng dụng - CS313.N21/Education_dataset_V2/sinhvien_dtb_toankhoa.xlsx')

In [3]:
df

,mssv,dtb_toankhoa,dtb_tichluy,sotc_tichluy
0,C410FEC4XPvAibaEXe/odi52as1TQ/z6UAtEIyTx,7.00,7.00,144.0
1,4555C74CXPvAibaEXe8UBGVVSBKSkjQKdKZAX7FE,6.34,6.34,153.0
2,6FB8C971XPvAibaEXe8zjuWfAVBr9Syz83phZPbU,2.31,0.00,0.0
3,7D7299A4XPvAibaEXe9hYalhCsDQbVspsqAf44vo,8.21,8.21,148.0
4,590263C4XPvAibaEXe9mDsFtgVHJ/lr5wIkYTfyo,8.32,8.32,148.0
...,...,...,...,...
13965,23418DFBXPvAibaEXe8fkFoA0ROB11ZORpcgaZsN,3.33,0.00,0.0
13966,7CDE61ABXPvAibaEXe/VxWgTgtHe04Encl5UmaMi,8.59,8.59,9.0
13967,658FB4D5XPvAibaEXe/VxWgTgtHe02gf1ImYGwpE,8.50,8.50,9.0
13968,7114E632XPvAibaEXe/VxWgTgtHe08jgqfqtydmc,5.16,6.32,5.0
13969,F3DA4B4EXPvAibaEXe/jswsdDHMZJUhPMDC53M8G,0.00,0.00,0.0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13970 entries, 0 to 13969
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mssv          13970 non-null  object
 1   dtb_toankhoa  13648 non-null  float64
 2   dtb_tichluy   13648 non-null  float64
 3   sotc_tichluy  13648 non-null  float64
dtypes: float64(3), object(1)
memory usage: 436.7+ KB

In [67]:
df_Khuvuc = pd.read_excel('/content/thpr (version 1).xlsx',sheet_name =  'Table 2')

In [68]:
df_Khuvuc

,STT,Ma Tinh,Tên Tỉnh/TP,Mã Quận/Huyện,Tên Quận/Huyện,MÃ TRƯỜNG,TEN_TRUONG,Địa Chỉ,KHU_VUC,Trường DTNT
0,0,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN
1,1,01,Hà Nội,00,Sở Giáo dục và Đào tạo,800,Học ở nước ngoài,NaN,Khu vực 3,Không
2,2,01,Hà Nội,00,Sở Giáo dục và Đào tạo,900,"Quân nhân, Công an tại ngũ",NaN,Khu vực 3,Không
3,3,01,Hà Nội,01,Quận Ba Đình,062,THPT Nguyễn Trãi-Ba Đình,"Số 50 phố Nam Cao, phường Giảng Võ, quận Ba Đ...",Khu vực 3,Không
4,4,01,Hà Nội,01,Quận Ba Đình,066,THPT Phan Đình Phùng,"Số 30, phố Phan Đình Phùng, phường Quán Thánh...",Khu vực 3,Không
...,...,...,...,...,...,...,...,...,...,...
4887,5337,64,Hậu Giang,9,Thành phố Ngã Bảy,411,THPT Nguyễn Minh Quang (Từ\n01/02/2020),"Phường Lái Hiếu, Thành phố Ngã Bảy",Khu vực 1,Không
4888,5338,64,Hậu Giang,9,Thành phố Ngã Bảy,435,TT GDNN-GDTX thành phố Ngã\nBảy (Từ 01/02/2020),"Phường Lái Hiếu, thành phố Ngã Bảy",Khu vực 1,Không
4889,5339,64,Hậu Giang,9,Thành phố Ngã Bảy,440,THPT Lê Qúy Đôn (Từ 01/02/2020),"Phường Lái Hiếu, Thành phố Ngã Bảy",Khu vực 1,Không
4890,5340,65,Cục nhà trường,1,Cục Nhà trường - Hà Nội,1,Trường Đại học văn hóa nghệ thuật\nQuân đội,Số 67B phố Cửa Bắc- Quận Ba Đình,Khu vực 3,Không
4891,5341,65,Cục nhà trường,2,Cục Nhà trường - Đồng Nai,2,Trường Cao đẳng nghề Số 8,NaN,Khu vực 2,Không

In [69]:
df_Khuvuc.head(10)

,STT,Ma Tinh,Tên Tỉnh/TP,Mã Quận/Huyện,Tên Quận/Huyện,MÃ TRƯỜNG,TEN_TRUONG,Địa Chỉ,KHU_VUC,Trường DTNT
0,0,0,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN
1,1,01,Hà Nội,00,Sở Giáo dục và Đào tạo,800,Học ở nước ngoài,NaN,Khu vực 3,Không
2,2,01,Hà Nội,00,Sở Giáo dục và Đào tạo,900,"Quân nhân, Công an tại ngũ",NaN,Khu vực 3,Không
3,3,01,Hà Nội,01,Quận Ba Đình,062,THPT Nguyễn Trãi-Ba Đình,"Số 50 phố Nam Cao, phường Giảng Võ, quận Ba Đ...",Khu vực 3,Không
4,4,01,Hà Nội,01,Quận Ba Đình,066,THPT Phan Đình Phùng,"Số 30, phố Phan Đình Phùng, phường Quán Thánh...",Khu vực 3,Không
5,5,01,Hà Nội,01,Quận Ba Đình,068,THPT Phạm Hồng Thái,"Số 1 Phố Nguyễn Văn Ngọc, phường Cống Vị, quậ...",Khu vực 3,Không
6,6,01,Hà Nội,01,Quận Ba Đình,088,"TH,THCS&THPT Thực nghiệm Khoa học Giáo dục","Số 50 đường Liễu Giai, phường Cống Vị, quận B...",Khu vực 3,Không
7,7,01,Hà Nội,01,Quận Ba Đình,211,THPT Đinh Tiên Hoàng-Ba Đình,"Số 67 Phó Đức Chính, phường Trúc Bạch, quận B...",Khu vực 3,Không
8,8,01,Hà Nội,01,Quận Ba Đình,223,THPT Hoàng Long,"Số 347, phố Đội Cấn, quận Ba Đình, TP Hà Nội",Khu vực 3,Không
9,9,01,Hà Nội,01,Quận Ba Đình,401,GDNN-GDTX quận Ba Đình,"Số 1 Ngõ 294 Đội Cấn, phường Cống Vị, quận Ba...",Khu vực 3,Không

In [70]:
df_Khuvuc.dropna(subset = df_Khuvuc.columns[1],inplace = True)

In [71]:
df_Khuvuc.columns = df_Khuvuc.columns.str.strip()

In [76]:
df_Khuvuc.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4884 entries, 0 to 4891
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   STT             4884 non-null   object
 1   Ma Tinh         4884 non-null   object
 2   Tên Tỉnh/TP     4883 non-null   object
 3   Mã  Quận/Huyện  4883 non-null   object
 4   Tên Quận/Huyện  4883 non-null   object
 5   MÃ TRƯỜNG       4884 non-null   object
 6   TEN_TRUONG      4873 non-null   object
 7   Địa Chỉ         4760 non-null   object
 8   KHU_VUC         4835 non-null   object
 9   Trường  DTNT    4882 non-null   object
dtypes: object(10)
memory usage: 419.7+ KB

In [73]:
df_Khuvuc[df_Khuvuc.columns[1]].isna().sum()

0

In [77]:
tinh = df_Khuvuc[df_Khuvuc.columns[1]].astype(int)

In [79]:
truong = df_Khuvuc[df_Khuvuc.columns[5]].astype(int)

In [83]:
df_tinh = pd.DataFrame({'lop12_matinh':tinh,'lop12_matruong':truong,'khuvuc':df_Khuvuc[df_Khuvuc.columns[8]]})

In [84]:
df_tinh

      lop12_matinh  lop12_matruong      khuvuc
0                0               0         NaN
1                1             800  Khu vực 3
2                1             900  Khu vực 3
3                1              62  Khu vực 3
4                1              66  Khu vực 3
...            ...             ...         ...
4887            64             411   Khu vực 1
4888            64             435   Khu vực 1
4889            64             440   Khu vực 1
4890            65               1   Khu vực 3
4891            65               2   Khu vực 2

[4884 rows x 3 columns]

In [85]:
df_tinh.to_csv('/content/tinh.csv')